### PR TITLE
Update github actions and readme

### PR DESCRIPTION
**Pull request by grandima**

### CODE REVIEW

**Review by Artemka374 — CHANGES_REQUESTED** [review]
Some integration tests are failing, but CI passes, fix pls

**Review by coreggon11 — APPROVED** [review]
gj

**Comment by coreggon11** [comment]
can you merge https://github.com/Brushfam/openbrush-contracts/pull/57 into this branch?

**Comment by grandima** [comment]
> can you merge #57 into this branch?

done.

**Review by coreggon11 — APPROVED** [review]

**Review by Artemka374 — APPROVED** [review]

**Pull request merged**
